---

- hosts: all:!nameservers:!proxmoxhost
  vars:
    - domain: apprentice.local
  serial: 1
  roles:
    - role: dns

- hosts: nameservers
  tasks:
    - name: restart nameservers
      service:
        name: named
        state: restarted