
---

- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ip_prefix: 192.168.0
    ip_range: 101-199
  roles:
    - nmap

- hosts: discovered
  gather_facts: true

- hosts: dnsservers
  gather_facts: false
  vars:
    dns_domain: theodore.local
  roles:
    - dns
