
---
- hosts: pvehosts
  vars:
    pve_storage:  local-lvm
    pve_memory:   256
  vars_prompt:
  - name: pve_vmid
    prompt: "VM ID"
    private: no
  - name: pve_hostname
    prompt: Hostname
    private: no
  tasks:

    - name: create lxc container
      shell: pct create {{ pve_vmid }} /var/lib/vz/template/cache/centos-7-default_20170307_amd64.tar.gz -hostname {{ pve_hostname }} -storage {{ pve_storage }} -ssh-public-keys ~/.ssh/id_rsa.pub -memory 256 -swap 256 -net0 name=eth0,bridge=vmbr0,gw=192.168.0.1,ip=192.168.0.{{ pve_vmid }}/24
