---

- name: add forward rule
  lineinfile:
    path: /etc/named/forward.{{ ansible_domain }}
    regexp: "^{{ ansible_hostname }}.{{ ansible_domain }}.\tIN\tA"
    line: "{{ ansible_hostname }}.{{ ansible_domain }}.	IN	A	{{ ansible_default_ipv4.address }}"
  notify: restart dns
  delegate_to: "{{ item }}"
  with_items: "{{ groups['dnsservers']}}"

- name: add reverse rule
  lineinfile:
    path: /etc/named/reverse.{{ ansible_domain }}
    regexp: "^{{ ansible_default_ipv4.address.split('.')[3] }}\tIN\tPTR"
    line: "{{ ansible_default_ipv4.address.split('.')[3] }}	IN	PTR	{{ ansible_hostname }}.{{ ansible_domain }}."
  notify: restart dns
  delegate_to: "{{ item }}"
  with_items: "{{ groups['dnsservers']}}"