---

- name: update system
  yum:
    name: '*'
    state: latest

- name: install common packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - nano
    - net-tools
    - unzip
    - wget
    - zip
