---

- name: scan ip range
  shell: "nmap -sn -n {{ ip_prefix }}.{{ ip_range }} | grep -o {{ ip_prefix }}.*"
  register: hosts
  
- name: add discovered hosts
  add_host: name="{{ item }}" group=discovered
  with_items: "{{ hosts.stdout_lines }}"
