---

- name: "update /etc/named/forward.{{ domain }}"
  blockinfile:
    dest: /etc/named/forward.apprentice.local
    block: |
      @ IN A {{ ansible_default_ipv4.address }}
      {{ ansible_hostname }} IN A {{ ansible_default_ipv4.address }}
    marker: "; {{ ansible_default_ipv4.address }} {mark}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['nameservers'] }}"
  
- name: "update /etc/named/reverse.{{ domain }}"
  blockinfile:
    dest: /etc/named/reverse.apprentice.local
    block: |
      {{ ansible_default_ipv4.address.split('.')[3] }} IN PTR {{ ansible_hostname }}.{{ domain }}.
      {{ ansible_hostname }} IN A {{ ansible_default_ipv4.address }}
    marker: "; {{ ansible_default_ipv4.address }} {mark}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['nameservers'] }}"