---

- name: security | install packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
     - yum-cron
  notify: security | restart services

- name: security | disable password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify: restart sshd

#      - fail2ban # Do I need it?
#      - logwatch
