---

- hosts: localhost
  connection: local
  vars_prompt:
    - name: lxc_vmid
      prompt: ID
      private: no
    - name: lxc_hostname
      prompt: Hostname
      private: no
    - name: temp_lxc_ostemplate
      prompt: Template
      private: no
      default: centos
  vars:
    pve_api_host: 192.168.0.100
    pve_api_user: root@pam
    pve_node: apprentice
    lxc_ostemplate: "local:vztmpl/{{ temp_lxc_ostemplate }}.tar.gz"
    lxc_cpus: 2
    lxc_disk: 1
    lxc_net_gw: 192.168.0.1
    lxc_net_ip: 192.168.0.{{ lxc_vmid }}
    lxc_net_subnet: 24
    lxc_net_bridge: vmbr0
    lxc_pubkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  roles:
    - lxc-container
  tasks:
    - add_host: hostname="{{ lxc_net_ip }}" groups=lxc-container

- hosts: lxc-container
  roles:
    - common
