---

- name: create container
  shell: |
    pct create {{ proxmox_vmid }} /var/lib/vz/template/cache/centos-7-default_20161207_amd64.tar.xz \
      -hostname {{ proxmox_hostname }} \
      -storage local-lvm \
      -ssh-public-keys ~/.ssh/id_rsa.pub \
      -memory 256 -swap 256 \
      -net0 name=eth0,bridge=vmbr0,gw=192.168.0.1,ip=192.168.0.{{ proxmox_vmid }}/24

- name: start container
  proxmox:
    vmid: "{{ proxmox_vmid }}"
    api_user: root@pam
    api_password: "{{ proxmox_api_password }}"
    api_host: 192.168.0.100
    state: started

- name: wait 5 seconds for network
  pause:
    seconds: 5

- name: install sshd onto container
  shell: pct exec {{ proxmox_vmid }} -- bash -c 'yum install -y openssh-server'

- name: start sshd on container
  shell: pct exec {{ proxmox_vmid }} -- bash -c 'systemctl start sshd'
