
---
- hosts: test
  vars_prompt:
  - name: "site"
    prompt: "Domain"
    private: no
  tasks:

    - name: install or update httpd
      yum:
        name: httpd
        state: latest

    - name: create document root
      file:
        path: /var/www/{{site}}/html
        state: directory

    - name: create vhost config
      template:
          src: vhost.conf.j2
          dest: /etc/httpd/conf.d/{{site}}.conf

    - name: Restart httpd
      systemd:
        name: httpd
        state: restarted
